name: contracts-dbt
source:
  dbt:
    auto_compile: true
    disable_manifest: false
    project_path: .
target:
  fastapi:
    path: app/models
    repo: OGsiji/test-api-model
    type: github
validation:
  fail_on:
  - missing_tables
  - missing_required_columns
  warn_on:
  - type_mismatches
version: '1.0'
